// <auto-generated />
using System;
using AGenerator.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AGenerator.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("AGenerator.Models.Act", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ActDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdditionalInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Appendix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AuthorSupervisionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConstructionObjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContractorOrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContractorRepId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CopiesCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CustomerOrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomerRepId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DesignerOrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DesignerRepId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DrawingNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EquipmentUsed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullLoadConditions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("GenContractorOrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GenContractorRepId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GenContractorSkRepId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GeneratedFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GeoCondition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InAxes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IntervalType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Level1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Level2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Level3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LoadPercentage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mark")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialsUsed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OtherPerson1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OtherPerson2Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OtherPerson3Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectDocumentation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProtocolDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("QualityControl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RelatedActId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RelatedAookId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SafetyMeasures")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StandardReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubsequentWork")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsageAsIntended")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Volume")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WeatherCondition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WorkEndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WorkStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkVolume")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConstructionObjectId");

                    b.HasIndex("ContractorOrganizationId");

                    b.HasIndex("ContractorRepId");

                    b.HasIndex("CustomerOrganizationId");

                    b.HasIndex("CustomerRepId");

                    b.HasIndex("DesignerOrganizationId");

                    b.HasIndex("DesignerRepId");

                    b.HasIndex("GenContractorOrganizationId");

                    b.HasIndex("GenContractorRepId");

                    b.HasIndex("GenContractorSkRepId");

                    b.HasIndex("OtherPerson1Id");

                    b.HasIndex("OtherPerson2Id");

                    b.HasIndex("OtherPerson3Id");

                    b.HasIndex("RelatedActId");

                    b.HasIndex("RelatedAookId");

                    b.ToTable("Acts");
                });

            modelBuilder.Entity("AGenerator.Models.ActMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActId");

                    b.HasIndex("MaterialId");

                    b.ToTable("ActMaterials");
                });

            modelBuilder.Entity("AGenerator.Models.ActProjectDoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectDocId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActId");

                    b.HasIndex("ProjectDocId");

                    b.ToTable("ActProjectDocs");
                });

            modelBuilder.Entity("AGenerator.Models.ActSchema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActId");

                    b.HasIndex("SchemaId");

                    b.ToTable("ActSchemas");
                });

            modelBuilder.Entity("AGenerator.Models.ConstructionObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Contractor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractorRequisites")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerRequisites")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DefaultContractorOrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DefaultCustomerOrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DefaultDesignerOrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DefaultGenContractorOrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DesignerRequisites")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DefaultContractorOrganizationId");

                    b.HasIndex("DefaultCustomerOrganizationId");

                    b.HasIndex("DefaultDesignerOrganizationId");

                    b.HasIndex("DefaultGenContractorOrganizationId");

                    b.ToTable("Objects");
                });

            modelBuilder.Entity("AGenerator.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConstructionObjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludeOrganizationInAct")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NrsDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NrsNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationRequisites")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("WorkEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WorkStartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConstructionObjectId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("AGenerator.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CertificateDateText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificateFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificateNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConstructionObjectId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocumentType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GostNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConstructionObjectId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("AGenerator.Models.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Requisites")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("AGenerator.Models.ProjectDoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConstructionObjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GIP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sheets")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConstructionObjectId");

                    b.ToTable("ProjectDocs");
                });

            modelBuilder.Entity("AGenerator.Models.Protocol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConstructionObjectId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocumentType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Laboratory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActId");

                    b.HasIndex("ConstructionObjectId");

                    b.ToTable("Protocols");
                });

            modelBuilder.Entity("AGenerator.Models.Schema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConstructionObjectId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConstructionObjectId");

                    b.ToTable("Schemas");
                });

            modelBuilder.Entity("AGenerator.Models.Act", b =>
                {
                    b.HasOne("AGenerator.Models.ConstructionObject", "ConstructionObject")
                        .WithMany("Acts")
                        .HasForeignKey("ConstructionObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGenerator.Models.Organization", "ContractorOrganization")
                        .WithMany()
                        .HasForeignKey("ContractorOrganizationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AGenerator.Models.Employee", "ContractorRep")
                        .WithMany()
                        .HasForeignKey("ContractorRepId");

                    b.HasOne("AGenerator.Models.Organization", "CustomerOrganization")
                        .WithMany()
                        .HasForeignKey("CustomerOrganizationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AGenerator.Models.Employee", "CustomerRep")
                        .WithMany()
                        .HasForeignKey("CustomerRepId");

                    b.HasOne("AGenerator.Models.Organization", "DesignerOrganization")
                        .WithMany()
                        .HasForeignKey("DesignerOrganizationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AGenerator.Models.Employee", "DesignerRep")
                        .WithMany()
                        .HasForeignKey("DesignerRepId");

                    b.HasOne("AGenerator.Models.Organization", "GenContractorOrganization")
                        .WithMany()
                        .HasForeignKey("GenContractorOrganizationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AGenerator.Models.Employee", "GenContractorRep")
                        .WithMany()
                        .HasForeignKey("GenContractorRepId");

                    b.HasOne("AGenerator.Models.Employee", "GenContractorSkRep")
                        .WithMany()
                        .HasForeignKey("GenContractorSkRepId");

                    b.HasOne("AGenerator.Models.Employee", "OtherPerson1")
                        .WithMany()
                        .HasForeignKey("OtherPerson1Id");

                    b.HasOne("AGenerator.Models.Employee", "OtherPerson2")
                        .WithMany()
                        .HasForeignKey("OtherPerson2Id");

                    b.HasOne("AGenerator.Models.Employee", "OtherPerson3")
                        .WithMany()
                        .HasForeignKey("OtherPerson3Id");

                    b.HasOne("AGenerator.Models.Act", "RelatedAct")
                        .WithMany()
                        .HasForeignKey("RelatedActId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AGenerator.Models.Act", "RelatedAook")
                        .WithMany()
                        .HasForeignKey("RelatedAookId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ConstructionObject");

                    b.Navigation("ContractorOrganization");

                    b.Navigation("ContractorRep");

                    b.Navigation("CustomerOrganization");

                    b.Navigation("CustomerRep");

                    b.Navigation("DesignerOrganization");

                    b.Navigation("DesignerRep");

                    b.Navigation("GenContractorOrganization");

                    b.Navigation("GenContractorRep");

                    b.Navigation("GenContractorSkRep");

                    b.Navigation("OtherPerson1");

                    b.Navigation("OtherPerson2");

                    b.Navigation("OtherPerson3");

                    b.Navigation("RelatedAct");

                    b.Navigation("RelatedAook");
                });

            modelBuilder.Entity("AGenerator.Models.ActMaterial", b =>
                {
                    b.HasOne("AGenerator.Models.Act", "Act")
                        .WithMany("ActMaterials")
                        .HasForeignKey("ActId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGenerator.Models.Material", "Material")
                        .WithMany("ActMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Act");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("AGenerator.Models.ActProjectDoc", b =>
                {
                    b.HasOne("AGenerator.Models.Act", "Act")
                        .WithMany("ActProjectDocs")
                        .HasForeignKey("ActId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGenerator.Models.ProjectDoc", "ProjectDoc")
                        .WithMany("ActProjectDocs")
                        .HasForeignKey("ProjectDocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Act");

                    b.Navigation("ProjectDoc");
                });

            modelBuilder.Entity("AGenerator.Models.ActSchema", b =>
                {
                    b.HasOne("AGenerator.Models.Act", "Act")
                        .WithMany("ActSchemas")
                        .HasForeignKey("ActId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGenerator.Models.Schema", "Schema")
                        .WithMany("ActSchemas")
                        .HasForeignKey("SchemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Act");

                    b.Navigation("Schema");
                });

            modelBuilder.Entity("AGenerator.Models.ConstructionObject", b =>
                {
                    b.HasOne("AGenerator.Models.Organization", "DefaultContractorOrganization")
                        .WithMany()
                        .HasForeignKey("DefaultContractorOrganizationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AGenerator.Models.Organization", "DefaultCustomerOrganization")
                        .WithMany()
                        .HasForeignKey("DefaultCustomerOrganizationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AGenerator.Models.Organization", "DefaultDesignerOrganization")
                        .WithMany()
                        .HasForeignKey("DefaultDesignerOrganizationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AGenerator.Models.Organization", "DefaultGenContractorOrganization")
                        .WithMany()
                        .HasForeignKey("DefaultGenContractorOrganizationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DefaultContractorOrganization");

                    b.Navigation("DefaultCustomerOrganization");

                    b.Navigation("DefaultDesignerOrganization");

                    b.Navigation("DefaultGenContractorOrganization");
                });

            modelBuilder.Entity("AGenerator.Models.Employee", b =>
                {
                    b.HasOne("AGenerator.Models.ConstructionObject", "ConstructionObject")
                        .WithMany("Employees")
                        .HasForeignKey("ConstructionObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConstructionObject");
                });

            modelBuilder.Entity("AGenerator.Models.Material", b =>
                {
                    b.HasOne("AGenerator.Models.ConstructionObject", "ConstructionObject")
                        .WithMany("Materials")
                        .HasForeignKey("ConstructionObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConstructionObject");
                });

            modelBuilder.Entity("AGenerator.Models.ProjectDoc", b =>
                {
                    b.HasOne("AGenerator.Models.ConstructionObject", "ConstructionObject")
                        .WithMany("ProjectDocs")
                        .HasForeignKey("ConstructionObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConstructionObject");
                });

            modelBuilder.Entity("AGenerator.Models.Protocol", b =>
                {
                    b.HasOne("AGenerator.Models.Act", "Act")
                        .WithMany("Protocols")
                        .HasForeignKey("ActId");

                    b.HasOne("AGenerator.Models.ConstructionObject", "ConstructionObject")
                        .WithMany("Protocols")
                        .HasForeignKey("ConstructionObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Act");

                    b.Navigation("ConstructionObject");
                });

            modelBuilder.Entity("AGenerator.Models.Schema", b =>
                {
                    b.HasOne("AGenerator.Models.ConstructionObject", "ConstructionObject")
                        .WithMany("Schemas")
                        .HasForeignKey("ConstructionObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConstructionObject");
                });

            modelBuilder.Entity("AGenerator.Models.Act", b =>
                {
                    b.Navigation("ActMaterials");

                    b.Navigation("ActProjectDocs");

                    b.Navigation("ActSchemas");

                    b.Navigation("Protocols");
                });

            modelBuilder.Entity("AGenerator.Models.ConstructionObject", b =>
                {
                    b.Navigation("Acts");

                    b.Navigation("Employees");

                    b.Navigation("Materials");

                    b.Navigation("ProjectDocs");

                    b.Navigation("Protocols");

                    b.Navigation("Schemas");
                });

            modelBuilder.Entity("AGenerator.Models.Material", b =>
                {
                    b.Navigation("ActMaterials");
                });

            modelBuilder.Entity("AGenerator.Models.ProjectDoc", b =>
                {
                    b.Navigation("ActProjectDocs");
                });

            modelBuilder.Entity("AGenerator.Models.Schema", b =>
                {
                    b.Navigation("ActSchemas");
                });
#pragma warning restore 612, 618
        }
    }
}
